import * as yup from "yup";
import { optionalField } from "Helpers/Validation";

const initialValues = () => ({
  tanf: "",
  ssi: "",
  ga: "",
  snap: "",
  rca: "",
  fosterChild: "",
  highPovertyArea: "",
  reducedLunch: "",
  receivingSnap: "",
  receivingPellGrant: "",
  ticketToWork: "",
  englishLearner: "",
  basicSkillsDeficient: "",
  homeless: "",
  runaway: "",
  fosterCare: "",
  exOffender: "",
  incarcerated: "",
  dateReleased: "",
  pregnantParenting: "",
  additionalAssistance: "",
  outOfHome: "",
  eligible: "",
  displacedHomemaker: "",
  withinTwoYearsTanf: "",
  hawaiianNative: "",
  singleParent: "",
  culturalBarriers: "",
  eligibleMigrantSeasonFarmworker: "",
  meetsGovernorsBarrier: "",
  gangStatus: "",
  incarceratedParent: "",
  paroleNumber: "",
  substanceAbuse: "",
});

const validationSchema = yup.object().shape({
  tanf: optionalField,
  ssi: optionalField,
  ga: optionalField,
  snap: optionalField,
  rca: optionalField,
  fosterChild: optionalField,
  highPovertyArea: optionalField,
  reducedLunch: optionalField,
  receivingSnap: optionalField,
  receivingPellGrant: optionalField,
  ticketToWork: optionalField,
  englishLearner: optionalField,
  basicSkillsDeficient: optionalField,
  homeless: optionalField,
  runaway: optionalField,
  fosterCare: optionalField,
  exOffender: optionalField,
  incarcerated: optionalField,
  dateReleased: optionalField,
  pregnantParenting: optionalField,
  additionalAssistance: optionalField,
  outOfHome: optionalField,
  eligible: optionalField,
  displacedHomemaker: optionalField,
  withinTwoYearsTanf: optionalField,
  hawaiianNative: optionalField,
  singleParent: optionalField,
  culturalBarriers: optionalField,
  eligibleMigrantSeasonFarmworker: optionalField,
  meetsGovernorsBarrier: optionalField,
  gangStatus: optionalField,
  incarceratedParent: optionalField,
  paroleNumber: optionalField,
  substanceAbuse: optionalField,
});

export { initialValues, validationSchema };
